---
### PHP 
- name: Install php
  hosts: all
  become: yes

  tasks:
  - name: Enable PHP
    shell: "amazon-linux-extras enable epel php7.2"
    become: yes


# install php-fpm
  - name: Install php-fpm
    yum:
      name:
        - php-fpm
        - php-mbstring
        - php-xml
        - php-cli
        - php-json
        - php-mysqlnd
        - php-pdo
        - php-common
      state: latest

  - name: start and enable php-fpm
    service:
      name: php-fpm
      state: started
      enabled: yes

 ###install MariaDB and phpMyAdmin

- name: Install mysql and phpmyadmin
  hosts: db
  become: yes

  tasks:
  - name: Install mariadb
    yum:
      name:
        - mariadb
        - mariadb-server
      state: latest

  - name: start mariadb
    service:
      name: mariadb
      enabled: true
      state: started

  - name: Creates phpmyadmin directory
    file:
      path: /usr/share/nginx/html/phpmyadmin/
      state: directory

  - name: Setup phpMyAdmin
    ansible.builtin.unarchive:
      src: https://www.phpmyadmin.net/downloads/phpMyAdmin-latest-all-languages.tar.gz
      dest: /usr/share/nginx/html/phpmyadmin
      extra_opts: [--strip-components=1]
      remote_src: yes
    notify:
      - Restart nginx
      - Restart php-fpm
      - Restart mariadb