FROM alpine:3.14

# install packages
RUN \
  echo "**** install build packages ****" && \
  apk add --no-cache \
    apache2-utils \
    curl \
    git \
    php7 \
    php7-fileinfo \
    php7-fpm \
    php7-json \
    php7-mysqli \
    php7-opcache \
    php7-iconv \
    php7-dom \
    php7-tokenizer \
    php7-curl \
    php7-zip \
    libressl3.3-libssl \
    logrotate \
    nano \
    nginx \
    openssl \
    php7-bz2 \
    php7-gd \
    php7-mbstring \
    php7-openssl \
    php7-session \
    php7-simplexml \
    php7-xml \
    php7-xmlwriter \
    php7-zlib && \ 
  # echo "**** configure nginx ****" && \
  # echo 'fastcgi_param  HTTP_PROXY         ""; # https://httpoxy.org/' >> \
  #   /etc/nginx/fastcgi_params && \
  # echo 'fastcgi_param  PATH_INFO          $fastcgi_path_info; # http://nginx.org/en/docs/http/ngx_http_fastcgi_module.html#fastcgi_split_path_info' >> \
  #   /etc/nginx/fastcgi_params && \
  # echo 'fastcgi_param  SCRIPT_FILENAME    $document_root$fastcgi_script_name; # https://www.nginx.com/resources/wiki/start/topics/examples/phpfcgi/#connecting-nginx-to-php-fpm' >> \
  #   /etc/nginx/fastcgi_params && \
  # rm -f /etc/nginx/http.d/default.conf && \
  echo "**** install phpmyadmin ****" && \
  mkdir -p /app/phpmyadmin && \
  curl -s -o \
    /tmp/phpmyadmin.tar.xz -L \
    "https://www.phpmyadmin.net/downloads/phpMyAdmin-latest-all-languages.tar.gz" && \
  tar xf \
    /tmp/phpmyadmin.tar.xz -C \
    /app/phpmyadmin/ --strip-components=1 && \
  sed -i "s@define('CONFIG_DIR'.*@define('CONFIG_DIR', '/config/phpmyadmin/');@" "/app/phpmyadmin/libraries/vendor_config.php" && \  
  sed -i 's@;clear_env = no@clear_env = no@' "/etc/php7/php-fpm.d/www.conf" && \
    rm -rf \
    /tmp/*
    

# add local files
COPY root/ /

# ports and volumes
EXPOSE 80 443
VOLUME /config