---
- name: Restart mariadb
  service:
    name: mariadb
    state: restarted
- name: Restart php-fpm
  service:
    name: php-fpm
    state: restarted
- name: Restart nginx
  service:
    name: nginx
    state: restarted
