---
# install nginx
- name: Install nginx
  hosts: all
  become: yes

  tasks:
  - name: Enable nginx and php for amazon linux 2
    shell: "amazon-linux-extras enable nginx1.12"
    become: yes

# install nginx
  - name: Install nginx
    yum:
      name: nginx
      update_cache: yes
      state: latest

  - name: start nginx and enable it
    service:
      name: nginx
      state: started
      enabled: yes