---
- name: Install nginx, php
  hosts: all
  become: yes

  tasks:
  - name: enable requarments in amazon-linux extras
    shell: "amazon-linux-extras enable nginx1.12 php7.2 epel"
    become: yes

  - name: Install nginx
    yum:
      name: nginx
      update_cache: yes
      state: latest

  - name: start/enable Nginx
    service:
      name: nginx
      state: started
      enabled: yes

  - name: Install php-fpm
    yum:
      name:
        - php-fpm
        - php-mbstring
        - php-xml
        - php-json
        - php-common
      state: latest

  - name: start php-fpm and enable it
    service:
      name: php-fpm
      state: started
      enabled: yes


- name: Install mysql and phpmyadmin
  hosts: phpmyadmin
  become: yes

  tasks:
  - name: Install mariadb
    yum:
      name:
        - mariadb
        - mariadb-server
      state: latest

  - name: start mariadb
    service:
      name: mariadb
      enabled: true
      state: started

  - name: Creates phpmyadmin directory
    file:
      path: /usr/share/nginx/html/phpmyadmin/
      state: directory

  - name: Setup phpMyAdmin
    ansible.builtin.unarchive:
      src: https://www.phpmyadmin.net/downloads/phpMyAdmin-latest-all-languages.tar.gz
      dest: /usr/share/nginx/html/phpmyadmin
      extra_opts: [--strip-components=1]
      remote_src: yes
    notify:
      - Restart nginx
      - Restart php-fpm
      - Restart mariadb
